version: '3.9'
services:
  app:
    container_name: auth_service
#    environment:
#      - POSTGRES_USER=${DB_USER}
#      - POSTGRES_PASSWORD=${DB_PASSWORD}
#      - POSTGRES_DB=${DB_NAME}
#      - DATABASE_HOST=${DB_HOST}
#      - DATABASE_PORT=${DB_PORT}
#      - TEST_POSTGRES_USER=${TEST_DB_USER}
#      - TEST_POSTGRES_PASSWORD=${TEST_DB_PASSWORD}
#      - TEST_POSTGRES_DB=${TEST_DB_NAME}
#      - TEST_DATABASE_HOST=${TEST_DB_HOST}
#      - TEST_DATABASE_PORT=${TEST_DB_PORT}
    tty: true
    build: .
    ports:
      - 9091:9091
    restart: unless-stopped
    depends_on:
      - postgresdb
    networks:
      - nettransfer

  postgresdb:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_DB: "habrdb"
      POSTGRES_USER: "habrpguser"
      POSTGRES_PASSWORD: "pgpwd4habr"
    restart: unless-stopped
    ports:
      - '54322:5432'
    networks:
      - nettransfer

  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6388:6379'
    networks:
      - nettransfer

networks:
  nettransfer:
    driver: bridge